# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f57b602153c603587958275c53807d3bdf26a98a02c0a5a5ec8afe20546c256b65717b5ee9832c44d82d83c8c8697e4cad6a38496f96e74c7fce56d094ff8163

test:
  secret_key_base: 95f5488a925a1ef5b4a0990948183149a51695726072d644cfdc4c926b32adfb0ec856b1030417c0408bca55209a085984ce6c1bd98404cecea65db788050d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
